### ISSUE TITLE
error when running ./buildF2MD

### ISSUE THREAD

**Issue by harirRzi** [josephkamel/F2MD#5]
Hi. Installed omnet++ (omnetpp-6.0pre15) and sumo previously on my macOs and I already could set up Veins and net on it correctly. Now I wanted to use your framework and I wrote the following command and it installed the framework successfully.

`git clone --recurse-submodules https://github.com/josephkamel/F2MD.git` 

but after running `./buildF2MD`, I got the following errors:

```
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.

/Users/F2MD/inet
/bin/sh: opp_makemake: command not found
make: *** [makefiles-so] Error 127
env: opp_makemake: No such file or directory
Traceback (most recent call last):
  File "/Users/F2MD/veins-f2md/./configure", line 78, in <module>
    subprocess.check_call(['env', 'opp_makemake'] + makemake_flags, cwd='src')
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['env', 'opp_makemake', '-f', '--deep', '--no-deep-includes', '--make-so', '-I', '.', '-o', 'veins', '-O', 'out', '-p', 'VEINS']' returned non-zero exit status 127.
env: opp_makemake: No such file or directory
Traceback (most recent call last):
  File "/Users/F2MD/veins-f2md/subprojects/veins_inet3/./configure", line 143, in <module>
    subprocess.check_call(['env', 'opp_makemake'] + makemake_flags, cwd='src')
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['env', 'opp_makemake', '-f', '--deep', '--no-deep-includes', '--make-so', '-I', '.', '-o', 'veins_inet', '-O', 'out', '-p', 'VEINS_INET', '-I../../../src', '-L../../../src', '-lveins$(D)', '-I../../../../inet/src', '-L../../../../inet/src', '-lINET$(D)', '-DINET_IMPORT']' returned non-zero exit status 127.
/bin/sh: opp_makemake: command not found
make: *** [makefiles] Error 127
```

**Comment by josephkamel** [comment]
F2MD is tested and working with SUMO version 1.2.1 and OMNETPP version 5.6.2 and only on Linux.

But it seems like in your case Java is missing on the machine?

The VM or the docker image maybe the best solution here.
